[emacs] Use gui emacs for e

diff --git a/bin/e b/bin/e
--- a/bin/e
+++ b/bin/e
@@ -16,6 +16,11 @@ usage() {
   grep '^#' <"$0" | tail -n +2 | cut -c 3-
 }
 
+if [[ -z "${DOTFILES_DIR}" ]]; then
+  echo "Error: DOTFILES_DIR not set"
+  exit 1
+fi
+
 if [[ $# == 0 ]]; then
   ARGS="$(
     fzf \
@@ -25,17 +30,20 @@ if [[ $# == 0 ]]; then
       --preview-window='right,75%,~1' \
       --preview="bat --color=always {}"
     )"
+  if [[ -z "$ARGS" ]]; then
+    exit 0
+  fi
+else
+  ARGS=${1:-.}
 fi
 
-if [[ -z "$ARGS" ]]; then
-  ARGS="${@:-.}"
-fi
+open -a "${DOTFILES_DIR}"/scripts/Emacs.app ${ARGS} &
 
-emacsclient \
-    --alternate-editor="" \
-    --no-window-system \
-    --quiet \
-    --suppress-output \
-    $ARGS
-
-reset
+# emacsclient \
+#     --alternate-editor="" \
+#     --no-window-system \
+#     --quiet \
+#     --suppress-output \
+#     $ARGS
+#
+# reset
